---
image: registry.pludoni.com/administrators/docker-images/rails-base:v202409
stages: [checks, test, deploy]

variables:
  deploy_host: 'product03'
  deploy_name: 'hrfilter'

include:
  - project: 'administrators/gitlab-ci-yml'
    file: '/rails_default.yml'

# bundle_audit:
#   script: |
#     gem install --force bundler-audit -N
#     bundle-audit update
#     bundle-audit check --ignore $IGNORE_CVE
