PREMAILER_SETTINGS = {
  line_length: 65,
  link_query_string: nil,
  base_url: nil,
  remove_classes: false,
  remove_ids: false,
  remove_comments: false,
  remove_scripts: true,
  css: [],
  css_to_attributes: true,
  with_html_string: false,
  css_string: nil,
  preserve_styles: false,
  preserve_reset: true,
  verbose: false,
  debug: false,
  io_exceptions: false,
  include_link_tags: true,
  include_style_tags: true,
  input_encoding: 'ASCII-8BIT',
  replace_html_entities: false,
}
Premailer::Rails.config.merge!(PREMAILER_SETTINGS)
